"""
Obsidian AI Brain - Phase 9: Export Knowledge
Purpose: Export notes as searchable website
Author: RAze
Date: 2026-07-08
"""

import json
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_html_page(notes, insights, graph_data):
    """Generate static HTML website."""
    
    html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🧠 My Knowledge Brain</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; color: #333; }
        header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 2rem; text-align: center; }
        header h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
        .container { max-width: 1200px; margin: 2rem auto; padding: 0 1rem; }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 2rem 0; }
        .stat-card { background: white; padding: 1.5rem; border-radius: 0.5rem; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }
        .stat-card h3 { color: #667eea; font-size: 2rem; margin: 0.5rem 0; }
        .stat-card p { color: #666; }
        .insights { background: white; padding: 2rem; border-radius: 0.5rem; margin: 2rem 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .insights h2 { color: #667eea; margin-bottom: 1rem; }
        .note-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1.5rem; margin: 2rem 0; }
        .note-card { background: white; padding: 1.5rem; border-radius: 0.5rem; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .note-card h3 { color: #667eea; margin-bottom: 0.5rem; }
        .note-card p { color: #666; line-height: 1.5; }
        footer { background: #333; color: white; padding: 1rem; text-align: center; margin-top: 2rem; }
    </style>
</head>
<body>
    <header>
        <h1>🧠 My Knowledge Brain</h1>
        <p>AI-enhanced personal knowledge management</p>
    </header>
    
    <div class="container">
        <!-- Stats -->
        <div class="stats">
            <div class="stat-card">
                <h3>""" + str(len(notes)) + """</h3>
                <p>Total Notes</p>
            </div>
            <div class="stat-card">
                <h3>""" + str(sum(n['readability']['total_words'] for n in notes)) + """</h3>
                <p>Total Words</p>
            </div>
            <div class="stat-card">
                <h3>""" + str(graph_data['stats']['total_edges']) + """</h3>
                <p>Connections</p>
            </div>
        </div>
        
        <!-- Insights -->
        <div class="insights">
            <h2>💡 Key Insights</h2>
            <p>""" + insights.get('vault_insights', 'Insights available') + """</p>
        </div>
        
        <!-- Notes -->
        <h2 style="color: #333; margin: 2rem 0 1rem 0;">📚 Your Notes</h2>
        <div class="note-list">
"""
    
    for note in notes[:20]:
        html += f"""
            <div class="note-card">
                <h3>{note['title']}</h3>
                <p>{note['content_preview']}</p>
                <p style="font-size: 0.9rem; color: #999; margin-top: 0.5rem;">
                    📁 {note['file_metadata']['folder']} • 📝 {note['readability']['total_words']} words
                </p>
            </div>
"""
    
    html += """
        </div>
    </div>
    
    <footer>
        <p>Generated by Obsidian AI Brain • Last updated """ + Path().cwd().name + """</p>
    </footer>
</body>
</html>
"""
    
    return html


def main():
    """Export knowledge."""
    print("\n" + "="*80)
    print("📤 OBSIDIAN AI BRAIN - EXPORT KNOWLEDGE")
    print("="*80)
    
    # Load data
    try:
        with open('data/enriched_notes.json', 'r') as f:
            notes = json.load(f)['notes']
        with open('data/insights.json', 'r') as f:
            insights = json.load(f)
        with open('data/graph_data.json', 'r') as f:
            graph_data = json.load(f)
    except Exception as e:
        print(f"⚠️  Error: {e}")
        return
    
    # Generate HTML
    logger.info("📄 Generating HTML website...")
    html = generate_html_page(notes, insights, graph_data)
    
    # Save
    output_dir = Path('exports')
    output_dir.mkdir(parents=True, exist_ok=True)
    
    index_file = output_dir / 'index.html'
    with open(index_file, 'w', encoding='utf-8') as f:
        f.write(html)
    
    logger.info(f"✅ Saved to {index_file}")
    
    print(f"\n✅ EXPORT COMPLETE!")
    print(f"   Website: {index_file}")
    print(f"   Open in browser to view")
    print("="*80)


if __name__ == "__main__":
    main()
